apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-img
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: default-conf
            mountPath: /etc/nginx/conf.d
      volumes:
      - name: default-conf
        configMap:
            name: phpmyadmin-config
            items:
            - key: default.conf
              path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name _;
      root /var/www/phpmyadmin;
      index index.php index.html;
      try_files $uri $uri/ =404;
    }